### ISSUE TITLE
ParsePreferencesException

### ISSUE THREAD

**Issue by a3349384** [shchurov/SharedPreferences-Editor-Plugin#2]
Error while parsing SharedPreferences file
I would really appreciate if you file this issue with the details here: https://github.com/shchurov/SharedPreferences-Editor-Plugin
Details: 
Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell echo $EXTERNAL_STORAGE
/sdcar
Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell mkdir -p /sdcar/prefs_editor/normal
Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell mkdir -p /sdcar/prefs_editor/unified
Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell rm -rf /sdcar/prefs_editor/normal/*
Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell rm -rf /sdcar/prefs_editor/unified/*
Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell run-as {packageName} chmod -R 777 /data/data/{packageName}/shared_prefs/
Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell cp /data/data/{packageName}/...

**Comment by mikehodz** [comment]
@a3349384, thanks for your report! 
I haven't checked whether it works on an emulator, will do it. Could you try to get full log? Usually when an error happens Idea shows pop-up in the bottom right corner. If you click on it it will open dialog window with all the details.

**Comment by a3349384** [comment]
Not only emulators,but also my Moto XT1254.
Here is the detail error message:
Details: Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell echo $EXTERNAL_STORAGE /sdcar Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell mkdir -p /sdcar/prefs_editor/normal Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell mkdir -p /sdcar/prefs_editor/unified Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell rm -rf /sdcar/prefs_editor/normal/\* Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell rm -rf /sdcar/prefs_editor/unified/\* Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell run-as {packageName} chmod -R 777 /data/data/{packageName}/shared_prefs/ Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell cp /data/data/{packageName}/shared_prefs/\* /sdcar/prefs_editor/normal Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell for f in /sdcar/prefs_editor/normal/*; do echo $f; done /sdcar/prefs_editor/normal/ Command: D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell mv /sdcar/prefs_editor/normal/normal /sdcar/prefs_editor/unified/pref0.xml Command: adb pull /sdcar/prefs_editor/unified C:\Users\ADMINI~1\AppData\Local\Temp\9157040969718287352 adb: error: remote object '/sdcar/prefs_editor/unified' does not exis

**Comment by mikehodz** [comment]
@a3349384, Ok I think here's the problem:

Command: `D:\android_sdk\platform-tools\adb.exe -s emulator-5554 shell for f in /sdcar/prefs_editor/normal/*; do echo $f; done`

And the output is:
`/sdcar/prefs_editor/normal/`

It seems like that folder is empty. Although this situation should be handled and show more accurate error message, are you sure that you have any SharedPreferences files in that project?

**Comment by a3349384** [comment]
No,it's a new emulator.But what does “/sdcar/prefs_editor/normal/” matter with my project?

**Comment by mikehodz** [comment]
@a3349384, Before pulling SharedPreferences files from the device it copies them to a tmp directory on the sdcard (`/sdcar/prefs_editor/normal/` in your case)

**Comment by a3349384** [comment]
OK,I see.

**Comment by mikehodz** [comment]
@a3349384, v1.07 is released, now it should show a correct error popup, could you check it?

**Comment by a3349384** [comment]
@shchurov Now it's OK,thanks for your work.
