### ISSUE TITLE
Plugin doesnt work

### ISSUE THREAD

**Issue by stillie** [shchurov/SharedPreferences-Editor-Plugin#4]
Good day,

I just installed your plug in, when i click the menu option, it does nothing.

**Comment by mikehodz** [comment]
Hi @stillie,
I haven't maintained the plugin in the last two years. Unfortunately, it's vulnerable to changes in Android Studio, Android Gradle plugin and ADB. So it's quite possible that something has changed in any of these dependencies and the plugin stopped working. 😔

**Comment by stillie** [comment]
ok thanks hey, maybe specify that in the description of the plug-in 

Thanks for the response
